---
# from https://github.com/goreleaser/nfpm/blob/main/.github/dependabot.yml
version: 2
multi-ecosystem-groups:
  combined:
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    patterns:
      - "*"
    multi-ecosystem-group: "combined"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    patterns:
      - "*"
    multi-ecosystem-group: "combined"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    patterns:
      - "*"
    multi-ecosystem-group: "combined"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    patterns:
      - "*"
    multi-ecosystem-group: "combined"
