FROM golang:1.23-bullseye

RUN go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest

# Run the binary.
ENTRYPOINT ["/go/bin/gomarkdoc", "--output", "/docs/docs.md", "/package/pkg/...", "/package/internal/...", "/package/cmd/..."]
