# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/photos2map /go/bin/photos2map
# Expose port for publishing as web service
# EXPOSE 8080
# Run the binary.
ENTRYPOINT ["/go/bin/photos2map"]
