---
version: "3"
services:
  golang-starter:
    container_name: golang-starter
    image: toozej/golang-starter:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.golang-starter.rule=Host(`golang-starter.test`)"
      # - "traefik.http.routers.golang-starter.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.golang-starter-secure.entrypoints=https"
      # - "traefik.http.routers.golang-starter-secure.rule=Host(`golang-starter.test`)"
      # - "traefik.http.routers.golang-starter-secure.middlewares=headers@file"
      # - "traefik.http.routers.golang-starter-secure.tls=true"
    # networks:
      # - traefik
